<?php 
include 'view/headers.php';
echo "<link rel='stylesheet' href='../style/playlist.css'>";
echo "<link rel='stylesheet' href='../style/trackes'>";
echo "<link rel='stylesheet' href='../style/radio.css'>";
?>

<?php 
include 'view/top.php';
include 'view/top-second.php';
?>
<div class="radio-setup">
    <div class="content-track">
            <div class="content-image">
                <img src="/images/Screenshot 2023-06-24 100429.png" alt="">
            </div>
            <div class="content-song-detail">
                <div class="content-song-name">wetata</div>
                <div>
                    <audio src="https://stream-154.zeno.fm/t5td4ky6hkeuv?zs=TzRUw_7XQbaIA8cEXbBt_g" id="id">
                        <source src="sounds/Wegdayit - Rega Bey Bereggae.mp3" type="audio/mpeg">
                    </audio>
                </div>
            </div>
    </div>

    <div class="content-track">
            <div class="content-image">
                <img src="/images/Screenshot 2023-06-24 100429.png" alt="">
            </div>
            <div class="content-song-detail">
                <div class="content-song-name">Sheger FM</div>
                <div>
                    <audio src="http://stream.zenolive.com/cwkxynwagt5tv" id="id">
                        <source src="sounds/Wegdayit - Rega Bey Bereggae.mp3" type="audio/mpeg">
                    </audio>
                </div>
            </div>
    </div>

    <div class="content-track">
            <div class="content-image">
                <img src="/images/Screenshot 2023-06-24 100429.png" alt="">
            </div>
            <div class="content-song-detail">
                <div class="content-song-name">BISRAT FM</div>
                <div>
                    <audio src="https://stream-159.zeno.fm/1cyn1as4v68uv?zs=yImzP1vkSCWja-MqfNhVxg" id="id">
                        <source src="sounds/Wegdayit - Rega Bey Bereggae.mp3" type="audio/mpeg">
                    </audio>
                </div>
            </div>
    </div>
  
    <div class="content-track">
            <div class="content-image">
                <img src="/images/Screenshot 2023-06-24 100429.png" alt="">
            </div>
            <div class="content-song-detail">
                <div class="content-song-name">EBC FM</div>
                <div>
                    <audio src="https://stream-156.zeno.fm/rb6wbrap7yzuv?zs=HdNGbcyZTUWhaRRIUg-e-w"id="id">
                        <source src="sounds/Wegdayit - Rega Bey Bereggae.mp3" type="audio/mpeg">
                    </audio>
                </div>
            </div>
    </div>
                    
<div class="sheger">
<p>SHEGER FM</p>
<audio controls>
    <source src="http://stream.zenolive.com/cwkxynwagt5tv" type="audio/mpeg">
    Your browser doesn't support the HTML5 <audio> tag.
        </audio>
    </div>
    <br>
    <div class="afro">

        <p>AFRO FM</p>
        <audio controls>
            <source src="http://stream.zeno.fm/fu367ky6hkeuv" type="audio/mpeg">
            Your browser doesn't support the HTML5 <audio> tag.
        </audio>    
    </div>
    <div class="anime">
        <p>anime FM</p>
        <audio controls>
            <source src="http://audio.misproductions.com/japan128k" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <div class="Jazz">
        <p>jazz FM</p>
        <audio controls>
            <source src="http://64.95.243.43:8002/stream/1/" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <div class="Jazz">
        <p>jazz FM</p>
        <audio controls>
            <source src="http://144.217.158.59:5120/stream/1/" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <!-- #EXTINF:-1 tvg-logo="http://radio.pervii.com/im/0/1562988670.jpg" group-title="JAZZ Radio - radio.pervii.com", Smooth Jazz Florida Worldwide - 128 kbit/s
http://144.217.158.59:5120/stream/1/ -->
    <div class="rap">
        <p>Rap FM</p>
        <audio controls>
            <source src="http://streams.bigfm.de/bigfm-oldschool-128-mp3" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <!-- #EXTINF:-1 tvg-logo="http://radio.pervii.com/logo/94123.jpg" group-title="RAP Radio - radio.pervii.com", bigFM Oldschool Rap and HipHop - 128 kbit/s
http://streams.bigfm.de/bigfm-oldschool-128-mp3 -->
    <div class="rap">
        <p>Rap FM</p>
        <audio controls>
            <source src="http://streams.bigfm.de/bigfm-oldschool-64-aac" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <!-- #EXTINF:-1 tvg-logo="http://radio.pervii.com/logo/94123.jpg" group-title="RAP Radio - radio.pervii.com", bigFM Oldschool - 128 kbit/s
http://streams.bigfm.de/bigfm-oldschool-64-aac
-->
    <div class="ragge">
        <p>ragge FM</p>
        <audio controls>
            <source src="http://s02.whooshserver.net:9091/live.mp3" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <!-- #EXTINF:-1 tvg-logo="http://radio.pervii.com/im/7/1551266037.jpg" group-title="REGGAE Radio - radio.pervii.com", Vibesfm.net - 96 kbit/s
http://s02.whooshserver.net:9091/live.mp3
-->
    <div class="ragge">
        <p>ragge FM</p>
        <audio controls>
            <source src="http://hd.lagrosseradio.info:8000/lagrosseradio-reggae-192.mp3" type="audio/mpeg">
            <!-- Your browser doesn't support the HTML5 <audio> tag. -->
        </audio>
    </div>
    <!--#EXTINF:-1 tvg-logo="http://radio.pervii.com/logo/97181.jpg" group-title="REGGAE Radio - radio.pervii.com", La Grosse Radio Reggae - Dub Dancehall Roots - From Paris - www.LaGrosseRadio.com - 192 kbit/s
    http://hd.lagrosseradio.info:8000/lagrosseradio-reggae-192.mp3
-->

<div class="jano">
    <p>jano FM</p>
    <audio controls>
        <source src="https://stream-159.zeno.fm/1cyn1as4v68uv?zs=yImzP1vkSCWja-MqfNhVxg" type="audio/mpeg">
        <!-- https://zeno.fm/_next/image/?url=https%3A%2F%2Fimages.zeno.fm%2Fx_coSsapKlumm6aEXNn-8eGe8UaiLb6zlpJZSyuuCpM%2Frs%3Afit%3A320%3A320%2Fg%3Ace%3A0%3A0%2FaHR0cHM6Ly9lZGl0b3IuemVub21lZGlhLmNvbS9yZXNvdXJjZXMvenNfc3RhdGlvbi82MzgxNTMvQ2FyZFdlYnNpdGUvaW1hZ2UucG5n.webp&w=1200&q=75 -->
    </audio>
</div>
<div class="bisrat">
    <p>bisrat FM</p>
    <audio controls>
        <source src="https://stream-159.zeno.fm/1cyn1as4v68uv?zs=yImzP1vkSCWja-MqfNhVxg" type="audio/mpeg">
        <!-- https://zeno.fm/_next/image/?url=https%3A%2F%2Fimages.zeno.fm%2Fasp7NCS89bGnaFljjHVhLnrNVxV6Z1AF8qMslVR7GU0%2Frs%3Afit%3A268%3A268%2Fg%3Ace%3A0%3A0%2FaHR0cHM6Ly9zdHJlYW0tdG9vbHMuemVub21lZGlhLmNvbS9jb250ZW50L3N0YXRpb25zL2FneHpmbnBsYm04dGMzUmhkSE55TWdzU0NrRjFkR2hEYkdsbGJuUVlnSUNBNExMd3pnZ01DeElPVTNSaGRHbHZibEJ5YjJacGJHVVlnSUNRX0tMRHRRb01vZ0VFZW1WdWJ3L2ltYWdlLz91cGRhdGVkPTE2NjE1NzE1ODcwMDA.webp&w=384&q=75 -->
    </audio>
</div>
<div class="Ethio FM 107.8">
    <p>Ethio FM 107.8 FM</p>
    <audio controls>
        <source src="https://stream-159.zeno.fm/72y045deqeruv?zs=NWR3FVc8SbWUTdGL2_uzHQ" type="audio/mpeg">
        <!-- Your browser doesn't support the HTML5 <audio> tag. -->
    </audio>
</div>
<div class="walta">
    <p>walta </p>
    <audio controls>
        <source src="https://stream-154.zeno.fm/t5td4ky6hkeuv?zs=TzRUw_7XQbaIA8cEXbBt_g" type="audio/mpeg">
        <!-- https://zeno.fm/_next/image/?url=https%3A%2F%2Fimages.zeno.fm%2F9I98ubcjY1NFS-7DI09VXLbslkHcDFsPBBDo3a6DgUQ%2Frs%3Afit%3A240%3A240%2Fg%3Ace%3A0%3A0%2FaHR0cHM6Ly9zdHJlYW0tdG9vbHMuemVub21lZGlhLmNvbS9jb250ZW50L3N0YXRpb25zL2FneHpmbnBsYm04dGMzUmhkSE55TWdzU0NrRjFkR2hEYkdsbGJuUVlnSURBX0lLMWhnc01DeElPVTNSaGRHbHZibEJ5YjJacGJHVVlnSUNBZ0lEeWlBb01vZ0VFZW1WdWJ3L2ltYWdlLz91cGRhdGVkPTE2NjE3NjM1MDUwMDA.webp&w=1200&q=100
 -->
    </audio>
</div>
<div class="ebc">
    <p>ebc </p>
    <audio controls>
        <source src="https://stream-156.zeno.fm/rb6wbrap7yzuv?zs=HdNGbcyZTUWhaRRIUg-e-w" type="audio/mpeg">
        <!-- https://zeno.fm/_next/image/?url=https%3A%2F%2Fimages.zeno.fm%2F9I98ubcjY1NFS-7DI09VXLbslkHcDFsPBBDo3a6DgUQ%2Frs%3Afit%3A240%3A240%2Fg%3Ace%3A0%3A0%2FaHR0cHM6Ly9zdHJlYW0tdG9vbHMuemVub21lZGlhLmNvbS9jb250ZW50L3N0YXRpb25zL2FneHpmbnBsYm04dGMzUmhkSE55TWdzU0NrRjFkR2hEYkdsbGJuUVlnSURBX0lLMWhnc01DeElPVTNSaGRHbHZibEJ5YjJacGJHVVlnSUNBZ0lEeWlBb01vZ0VFZW1WdWJ3L2ltYWdlLz91cGRhdGVkPTE2NjE3NjM1MDUwMDA.webp&w=1200&q=100-->
    </audio>
</div>
</div>

<!-- from other file -- /view/top.php -->
<?php 
    include 'view/bottom.php'
?>

<script>
var contentTrack=document.querySelectorAll(".content-track");


var player=document.querySelector(".player");
var playSong=document.getElementById("playSong");
var pauseSong=document.getElementById("pauseSong");

var nextSong=document.getElementById("nextSong");
var prevSong=document.getElementById("prevSong");

nextSong.style.display="none";
prevSong.style.display="none";

var audio=document.getElementById("id");
var first=0;

var progress;

contentTrack.forEach(function(track){
    track.addEventListener("click",function(e){
        
        //  attempt 1 to stop a song when another is played
        // if(!first)
        //     first=1;
        // else
        //     audio.pause();
        //  attempt 1 to stop a song when another is played
            if(!audio.paused){
                audio.pause();
                audio=track.children[1].children[1].children[0];
                audio.play();
            }
            else
            {
                audio=track.children[1].children[1].children[0];
                if(audio.duration > 0 && !audio.paused)
                {
                    audio.pause();
                    playSong.textContent="pause_circle";
                }
                else
                {
                    audio.play();
                    playSong.textContent="play_arrow";
    
                }

                player.setAttribute("data-url",track.getAttribute("data-url"));
                console.log(player.getAttribute("data-url"));
            }
            

        })
    })

playSong.addEventListener("click",function(e){
    // audio.play();
    if(audio.duration > 0 && !audio.paused)
    {
        audio.pause();
        e.target.textContent="pause_circle";
    }
    else
    {
        audio.play();
        e.target.textContent="play_arrow";
    }
})

</script>